# Generated by Django 3.1.2 on 2020-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_movie_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-11-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
