# Generated by Django 3.1.2 on 2020-11-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_auto_20201111_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryStates',
            new_name='CategoryState',
        ),
    ]
