# Generated by Django 3.1.2 on 2020-11-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20201111_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategoryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.category')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.movie')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.categorystate')),
            ],
        ),
    ]
