# Generated by Django 3.1.2 on 2020-11-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_moviecategorystate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecategorystate',
            name='category',
        ),
    ]
