# Generated by Django 3.1.2 on 2020-11-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_remove_moviecategorystate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category_state',
            field=models.ManyToManyField(to='recommendation.CategoryState'),
        ),
        migrations.DeleteModel(
            name='MovieCategoryState',
        ),
    ]
