# Generated by Django 3.1.2 on 2020-11-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_auto_20201111_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionquestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendation.questionanswer'),
        ),
    ]
